### PR TITLE
Dynamically update copyright year.

### LINKED ISSUE #250: copyright date in footer should always extend 2007-$CURRENTYEAR

### PR DESCRIPTION
**Pull request by mstathers**
fixes #250

### CODE REVIEW

**Comment by mutantmonkey** [comment]
Hi Michael,

Thanks for your contribution! Unfortunately, we don't currently provide a now tag in the template, so the fix for this isn't this simple. Running the site with this change results in:
```python
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'now'.
```

**Comment by mstathers** [comment]
Ah, apologies! I must not have been paying enough attention and I thought this was django.

Updated (and properly tested) now. Let me know if you need anything else adjusted.

**Comment by echarlie** [comment]
I'll give it a quick test in a few hours and probably merge it, unless @mutantmonkey beats me to it.

**Comment by mutantmonkey** [comment]
Thanks again!

**Pull request merged**
